# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=100)),
                ('header_logo', models.ImageField(blank=True, upload_to=b'')),
                ('header_link_text_0', models.CharField(blank=True, max_length=100)),
                ('header_link_text_1', models.CharField(blank=True, max_length=100)),
                ('header_link_text_2', models.CharField(blank=True, max_length=100)),
                ('header_link_url_0', models.CharField(blank=True, max_length=100)),
                ('header_link_url_1', models.CharField(blank=True, max_length=100)),
                ('header_link_url_2', models.CharField(blank=True, max_length=100)),
                ('body_heading', models.TextField(blank=True)),
                ('body_pr_image', models.ImageField(blank=True, upload_to=b'')),
                ('body_bg_image', models.ImageField(blank=True, upload_to=b'')),
                ('body_buy_button', models.CharField(blank=True, max_length=1)),
                ('body_bb_code', models.TextField(blank=True)),
                ('body_bb_image', models.ImageField(blank=True, upload_to=b'')),
                ('body_bb_link', models.CharField(blank=True, max_length=100)),
                ('body_above_bb', models.TextField(blank=True)),
                ('body_below_bb', models.TextField(blank=True)),
                ('body_ivs', models.TextField(blank=True)),
                ('testimonial_heading', models.TextField(blank=True)),
                ('testimonial_slider', models.CharField(blank=True, max_length=1)),
                ('testimonial_ivs', models.TextField(blank=True)),
                ('video_urls', models.TextField(blank=True)),
                ('footer_address', models.CharField(blank=True, max_length=100)),
                ('footer_link_text_0', models.CharField(blank=True, max_length=100)),
                ('footer_link_text_1', models.CharField(blank=True, max_length=100)),
                ('footer_link_text_2', models.CharField(blank=True, max_length=100)),
                ('footer_link_url_0', models.CharField(blank=True, max_length=100)),
                ('footer_link_url_1', models.CharField(blank=True, max_length=100)),
                ('footer_link_url_2', models.CharField(blank=True, max_length=100)),
                ('footer_color_select', models.CharField(blank=True, max_length=100)),
                ('footer_font_size', models.CharField(blank=True, max_length=100)),
                ('footer_tracking_code', models.TextField(blank=True)),
                ('footer_facebook_title', models.CharField(blank=True, max_length=100)),
                ('footer_facebook_image', models.ImageField(blank=True, upload_to=b'')),
                ('footer_facebook_description', models.TextField(blank=True)),
                ('submit', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
