# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='header_logo',
            field=models.TextField(blank=True),
        ),
    ]
