# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180520_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
