# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 15:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180520_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_heading',
            field=tinymce.models.HTMLField(),
        ),
    ]
